server:
  port: 9000

spring:
  application:
    name: provider
  cloud:
     nacos:
       discovery:
         #集群配置nginx地址
         server-addr: 192.168.0.38:8848

#暴露监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
