server:
  port: 9004
spring:
  application:
    name: sentinel
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.39:8848
    sentinel:
      transport:
        #配置sentinel地址,端口
        dashboard: 192.168.0.39:8080
        port: 8719
        #客户端IP
        client-ip: 192.168.0.100


#暴露自己的端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
